### ISSUE TITLE
Grafi

### ISSUE THREAD

**Issue by jaanos** [Zulkinho/APPR-2014-15#2]
Kodo za grafe vključi nekam v program - lahko kar v `uvoz.r`, lahko pa narediš novo datoteko s končnico `.r`, ki jo potem pokličeš npr. iz glavnega programa (pazi na velikost črk!).

Grafi naj bodo čitljivi. Tako bi pri prvem grafu koristilo, če so pozicije napisane navpično (parameter `las = 2` pri `barplot`); lahko tudi prilagodiš velikost teh oznak s parametrom `cex.names` (privzeta vrednost je `1`).

Pri drugem grafu je morda nesmiselno prikazati vse igralce, saj ne boš mogel nikakor za vsak stolpec pojasniti, komu pripada (zaporedne številke pa tudi nič ne povedo). Bolje bo, če se omejiš na npr. nekaj najboljših strelcev - potem imaš lahko njihova imena (ali vsaj priimke) pod vsakim stolpcem.

Še to: primerno kodiranje znakov za datoteko `tabelanogometasev.csv` je `"Windows-1252"`. Tako ti bo pravilno uvozilo tudi ime `"Fàbregas"`.

**Comment by Zulkinho** [comment]
ko naredim urejeno podtabelo in spremenim na grafu graf se vedno jemlje pozicije po abecedi, jaz pa bi rad da bi bile v takem vrstnem redu kot v tabeli, v kateri so te pozicije podane, kako to naredim

**Comment by jaanos** [comment]
Ker rišeš iz `UREJENAPODTABELA`, so narisane vrednosti prave, imena pozicij pa niso - k parametru `names.arg` jih torej podaj z `rownames(UREJENAPODTABELA)`.

**Comment by Zulkinho** [comment]
ja hvala tudi sam sem ravno ugotovil to površnost, hvala vseeno.

**Comment by jaanos** [comment]
To je urejeno, tako da zapiram.
