### ISSUE TITLE
Kodiranje znakov in poročilo

### ISSUE THREAD

**Issue by jaanos** [Zulkinho/APPR-2014-15#4]
Datoteko `vizualizacija.r` imaš shranjeno v kodiranju znakov `Windows-1250`, tako da je pri meni ne izvede pravilno. Da bo v skladu s preostalim projektom, bo najbolje, če jo pretvoriš v UTF-8. Najlažje to storiš tako, da jo odpreš v RStudiu. Če namesto `"ô"` v `"Côte d'Ivoire"`vidiš vprašaj, v meniju _File_ izberi _Reopen with Encoding..._ in izberi **Windows-1250**. Ko imaš ta znak (pa tudi šumnike na koncu) pravilno prikazan, v meniju _File_ izberi _Save with Encoding..._ in izberi **UTF-8**. Da ne bo težav, v `projekt.r`pri vključevanju programa `vizualizacija.r` dodaj še parameter `encoding = "UTF-8"`.

Poročila ti ne prevede, ker imaš v datotekah `grafi.pdf` in `grafi1.pdf` samo eno stran, ti pa vključuješ prvi dve. Tako ju lahko vključiš kot
```LaTeX
\includepdf[pages={1}]{../slike/grafi.pdf}
```
in podobno še za drugega. Enako lahko narediš tudi za zemljevid, da bo večji in tako lepše berljiv.

**Comment by Zulkinho** [comment]
Nar3dil sem kot ste mi narocili. Prosim za informacijo ce je sedaj vse kot mora biti. Hvala

**Comment by jaanos** [comment]
Je vse v redu, tako da zapiram.

Mogoče še ena pripomba glede poročila: v besedilu imaš tudi imena datotek in spremenljivk - lepo bi bilo, če se ločijo od ostalega besedila, kar lahko dosežeš z ukazom `\verb`, npr.
```LaTeX
\verb|read.csv|
```
Tako se tudi znebiš problemov z morebitnimi posebnimi znaki. Znak `|` takoj za `\verb` služi kot oznaka za konec niza - po potrebi ga lahko zamenjaš (npr. `\verb+|+` ti izpiše ravno ta znak).
